# language: ruby
# rvm:
#   - 2.5
#   - jruby

# script:
#   - bundle exec rails db:migrate
#   - bundle exec rspec
# cache: bundler
# services:
#   - postgresql
# addons:
#   postgresql: "9.4"

install:
  - bundle update --bundler
  - bundle install
services:
  - postgresql
script:
  - bundle exec bin/rails db:create
  - bundle exec rails db:migrate
  - bundle exec rails db:environment:set RAILS_ENV=test
  - bundle exec rspec
